### ISSUE TITLE
芒果TV 突然不能下载了

### ISSUE THREAD

**Issue by cjjdaq** [jaysonlong/webvideo-downloader#101]
Listening on port 18888 for clients...

Receive: {
    "fileName": "暗格里的秘密.第20集.HD1080p",
    "linksurl": "https://pcvideotx.titan.mgtv.com/c1/2021/08/24_0/911549847C5737A3B2F8DC8B713EFBDC_20210824_1_1_1851_mp4/640D09259A6391493F30B11A2F391351.m3u8?arange=0&pm=B7h0zwqmu7ZocJjLcDN0H2IjX_43m559uvPC3TnCTQ7VI6lMxERjYpnLLYNL0PS4ukKYcFZWRA1TjUbNsM51bE8RArJSoYLFW4Zx3M2veP7Uq_pm1QLWyLBlTv7JBOa_yZfLiGNJLSJ0rToxlhXXAC6yU1gziyKvDokuCCXK9ykrYQdlWF3F0eN15C5Q9pUeYyJ9~1zdM3Q~GN~PEC~XWdVs~1Z0tti8ezyX61Nvha42HWjlXRLdqKEqfag929IvKkEah81DQH6yhpvz62dq4EkScBof5q~gk4vQVhJnOPI0lFcXGEdLs6gF8G87ywTwpOF0h~0E90kuzs3mFJwXt70fOuLkdnO8usQLTTn73Bn3zlSvw~sXEgKgoUzxUahDutkepkIhtglxc9yNyTjBBbX2hN4wUtFPRO_mAeplIMH4CIGsqyp81ZHt4fKIYjhF5uzZJZn4q1hdrbXaou3opm3Fu3_0izMEN9RAA1G7deWVWTHT&mr=_Gv5oMAzTa2RROMvUFc9gWkdMNkavug80LAmwnltXi7Y4lKjP95tqG_~S8JlgDalALzJ5~d0WQ_BM8_II2vHGv7~dT7aBqsjkm5BSV0lsNgdg5Ifa0D~dbSBCP9vhn3prnYSVlQgVvQlAMIsqUXcnwEpLSYMTNiTmsRUB2p_jEQ0Vok2mT1_tjhRSe35wfmYKJ_jzQ70joks1TQGb4IlcUn5tDWBzwGpSO7GpiO5wGlcT0iofzsNwVMBH2A8Tw8yyMzGCbDAT5psYTTm5AyX~QtY_vMcTf5bNvYVI6tWUEZFfHbCUQJA7oi6JVraforgh8eRR0KvnUcJAtFEYHHvRRXkKmCyETNe0oHxq9CqHww~h1bz2Nek5pv_a8qOfXOmiQJ_EuyNXIwObc_r5G_ABhvEhX1B78W9NoZqo22reLvjk6VgpkXBHTwufs0NxipDLWScXYl2jSFfS0gR93eFa0vY79c8eKgFWnRzv7jJN~j8UtWvSH~1xOR5lxiTbRoHVAxOokuFkwN6L_QYa0X~l0f~fv4dOgR_RHtiJB6dsYT19sKl6yQTd4IXydZF0e6PwMcVsaRDR1fhE0cVDAxqT9tbDGlQCEDoiPOBJZrglWpNSuItbRXJLF5zUoNM95zq_5LnO6Ckq0VuBHHiGcObp9MJ6i177Ra0&uid=209b4ac872593d533742105139b0256c&vcdn=0&scid=25015&cpno=6i06rp&ruid=95fa4d8e5f0940cc",
    "type": "link"
}

Handle: "暗格里的秘密.第20集.HD1080p"

匹配到294段视频，开始下载
-- dispatcher/downloadHls
并行32线程下载

----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\vd\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "d:\vd\downloader\dispatcher.py", line 131, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, correct)
  File "d:\vd\downloader\dispatcher.py", line 39, in _downloadHls
    self.downloader.downloadAll(urls, fileNames, headers, self.hlsThreadCnt)
  File "d:\vd\downloader\tools\downloader.py", line 174, in downloadAll
    self._waitUtilFinish()
  File "d:\vd\downloader\tools\downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "d:\vd\downloader\tools\utils.py", line 101, in request
    % (method, url, response.status_code))
Exception: GET https://pcvideotx.titan.mgtv.com/c1/2021/08/24_0/911549847C5737A3B2F8DC8B713EFBDC_20210824_1_1_1851_mp4/EA27AF5D742475CAF1525B9EC545E7F3_220080_230080_1481_v02_mp4.ts?arange=0&pm=B7h0zwqmu7ZocJjLcDN0H2IjX_43m559uvPC3TnCTQ7VI6lMxERjYpnLLYNL0PS4ukKYcFZWRA1TjUbNsM51bE8RArJSoYLFW4Zx3M2veP7Uq_pm1QLWyLBlTv7JBOa_yZfLiGNJLSJ0rToxlhXXAC6yU1gziyKvDokuCCXK9ykrYQdlWF3F0eN15C5Q9pUeYyJ9\u203e1zdM3Q\u203eGN\u203ePEC\u203eXWdVs\u203e1Z0tti8ezyX61Nvha42HWjlXRLdqKEqfag929IvKkEah81DQH6yhpvz62dq4EkScBof5q\u203egk4vQVhJnOPI0lFcXGEdLs6gF8G87ywTwpOF0h\u203e0E90kuzs3mFJwXt70fOuLkdnO8usQLTTn73Bn3zlSvw\u203esXEgKgoUzxUahDutkepkIhtglxc9yNyTjBBbX2hN4wUtFPRO_mAeplIMH4CIGsqyp81ZHt4fKIYjhF5uzZJZn4q1hdrbXaou3opm3Fu3_0izMEN9RAA1G7deWVWTHT&mr=_Gv5oMAzTa2RROMvUFc9gWkdMNkavug80LAmwnltXi7Y4lKjP95tqG_\u203eS8JlgDalALzJ5\u203ed0WQ_BM8_II2vHGv7\u203edT7aBqsjkm5BSV0lsNgdg5Ifa0D\u203edbSBCP9vhn3prnYSVlQgVvQlAMIsqUXcnwEpLSYMTNiTmsRUB2p_jEQ0Vok2mT1_tjhRSe35wfmYKJ_jzQ70joks1TQGb4IlcUn5tDWBzwGpSO7GpiO5wGlcT0iofzsNwVMBH2A8Tw8yyMzGCbDAT5psYTTm5AyX\u203eQtY_vMcTf5bNvYVI6tWUEZFfHbCUQJA7oi6JVraforgh8eRR0KvnUcJAtFEYHHvRRXkKmCyETNe0oHxq9CqHww\u203eh1bz2Nek5pv_a8qOfXOmiQJ_EuyNXIwObc_r5G_ABhvEhX1B78W9NoZqo22reLvjk6VgpkXBHTwufs0NxipDLWScXYl2jSFfS0gR93eFa0vY79c8eKgFWnRzv7jJN\u203ej8UtWvSH\u203e1xOR5lxiTbRoHVAxOokuFkwN6L_QYa0X\u203el0f\u203efv4dOgR_RHtiJB6dsYT19sKl6yQTd4IXydZF0e6PwMcVsaRDR1fhE0cVDAxqT9tbDGlQCEDoiPOBJZrglWpNSuItbRXJLF5zUoNM95zq_5LnO6Ckq0VuBHHiGcObp9MJ6i177Ra0&uid=209b4ac872593d533742105139b0256c&vcdn=0&scid=25015&cpno=6i06rp&ruid=95fa4d8e5f0940cc http响应: 403错误

试了好几部都这样

**Comment by cjjdaq** [comment]
def getText(url, headers = {}, **kargs):
    if not url.startswith('http'):
        # 读取本地文件
        with open(url, 'r', encoding="utf-8") as f:
            return f.read()
    response = request('GET', url, headers=headers, **kargs)
#添加
    response.encoding='utf-8'
#结束
    return response.text

**Comment by Sparh4wk** [comment]
I can dl it, if its this one https://w.mgtv.com/b/363132/13640166.html

**Comment by peedan** [comment]
I downloaded 暗格里的秘密.第20集 successfully, too.

Everytime I found that I cannot download some drama on some OTT, I ask for help to those friends who can download.
Today I cannot download a drama on iq.com, I try to **connect to network through another IP address**, then I download the same drama successfully.
However, I cannot download the drama after I change the IP address to the beginning one.
I don't know why but you may try  my method.
Maybe Jason can tell us why and try to make video-downloader better.

**Comment by donaghyXu** [comment]
> def getText(url, headers = {}, **kargs):
> if not url.startswith('http'):
> # 读取本地文件
> with open(url, 'r', encoding="utf-8") as f:
> return f.read()
> response = request('GET', url, headers=headers, **kargs)
> #添加
> response.encoding='utf-8'
> #结束
> return response.text

方法有效
