### ISSUE TITLE
iqiyi VIP 无法下载

### ISSUE THREAD

**Issue by markhavemann** [jaysonlong/webvideo-downloader#144]
共1段视频，正在获取各段视频的真实链接
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Download and Process Videos\Downloader\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "X:\Download and Process Videos\Downloader\downloader\dispatcher.py", line 120, in download
    videoType, headers, audioUrls, videoUrls, subtitles = api.parseSingleUrl(url, data)
  File "X:\Download and Process Videos\Downloader\downloader\api.py", line 122, in parseSingleUrl
    videoType, audioUrls, videoUrls, subtitles = parseIqiyiUrl(url, realData, headers)
  File "X:\Download and Process Videos\Downloader\downloader\api.py", line 88, in parseIqiyiUrl
    audioUrls, videoUrls = [], parseIqiyiInfoUrls(infoUrls, headers)
  File "X:\Download and Process Videos\Downloader\downloader\api.py", line 55, in parseIqiyiInfoUrls
    data = json.loads(tools.getText(url, headers, timeout=10))
  File "X:\Download and Process Videos\Downloader\downloader\tools\utils.py", line 109, in getText
    response = request('GET', url, headers=headers, **kargs)
  File "X:\Download and Process Videos\Downloader\downloader\tools\utils.py", line 100, in request
    raise Exception('%s %s http响应: %d错误' \55
Exception: GET http://pcw-data.video.iqiyi.com/videos/v0/20211014/7e/d8/b51f9871885c35f3d8ffda9b87dd6cb5.f4v?qd_tvid=134402100&qd_vipres=2&qd_index=1&qd_aid=127069501&qd_stert=0&qd_scc=a0f2d142c72b9e25c9a13023ab6152dd&qd_sc=37d43a92bb85e725fc5625a9f5768c73&qd_uid=1614601512&qd_vip=1&qd_src=01010031010000000000&qd_tm=1661697110859&qd_vipdyn=2&qd_k=f6dff2811cb094a654149d4955fcc484&qd_p=abd85628&ve= http响应: 405错误
----------------------------------------------------------------------------------------------------

**Comment by jaysonlong** [comment]
我现在没有VIP账号，无法修复
