### ISSUE TITLE
wetv download error

### ISSUE THREAD

**Issue by tears03927** [jaysonlong/webvideo-downloader#172]
There's an error when downloading video from wetv.
Can you help to check? Thank you a lot.

Listening on port 18888 for clients...

Receive: {
    "fileName": "니급아적희환_2회 - 온라인 시청 - WeTV",
    "linksurl": "https://ltsaws.wetvinfo.com/svp_50125/011F353244CC419FC0F9F7FE8CFA856A2C6196817F922DE612A35AF8E2EF69635BFBDC061EC344091A9AC6F96BBAAB76921467EC040001AD8E7F2A9BBF2F1397E0868BBBB54BD45F7345FCF943CBBD26415C6F489B35BC4C02E279A4BA024D61E82BDC0AF0910F9A2F6BA6D47F35D904A5BE44EECEDAB553854293380E30FD75D7/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f321003.ts.m3u8?ver=4|%ED%95%9C%EA%B5%AD%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BFE3CCB8A9032F56A7ABDA5AAB4D133C4CA4747FF5BF934B5010C2877CD89FE2EFE2283CF7B027E967D6550B47412C4797377AF9A8A629C2B26D23CD5A93E9630/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f350114.vtt?ver=4|%EC%98%81%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BCB30AABF402118507501B7DBA7F59967F9A595DF2634A0DC18C7D9E71B5FDE07DF947D8CE92BE4A3CAC6C902E20D40D60385D6DBF54D3A9CB860A2653395C101/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f227103.vtt?ver=4|%EC%A4%91%EA%B5%AD%EC%96%B4(%EA%B0%84%EC%B2%B4)|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BE7820B23047FA6735DA4B37AC7E3A628857C46A229149B8571798662EE0363DCB59782049C7B55B64F9115057A41FE2CB3506F9C886FFAB313F71C71C27643D3/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f919102.vtt?ver=4|%EC%A4%91%EA%B5%AD%EC%96%B4(%EB%B2%88%EC%B2%B4)|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BE0943EACEE04A6C2D20A4635C0B9F56BF5C8FBFCCB7EA2BDEFCB6F87AAC46C9334778E9B25DD5C4827393E9E730A7C21627899E9BB304C23F11BB7E537DC4E55/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f928105.vtt?ver=4|%ED%83%9C%EA%B5%AD%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9B04A00F4D5464C72A33A20B85FB8A10B1B34FB284645C6C22946146CA16B5B6F291475AA0F43FA9E03A87B762E93347698D5F8701B0A5BE32D2F8905C39612FA4/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f616106.vtt?ver=4|%EB%B2%A0%ED%8A%B8%EB%82%A8%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9B898C73457F31CA55C6A6DBE48A8D3275F49216E3F09AA2936A41DA939F78E56AB4A41ABD2BC11E0E9A289FBEC5CBB0E89B51368DA771557C42B9EAC0C25DEB28/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f443107.vtt?ver=4|%EC%9D%B8%EB%8F%84%EB%84%A4%EC%8B%9C%EC%95%84%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9B4A1FA2D7432A2B830E974C08FE5C0DBD4BBE199FFE670A9E91048B3161CB1E87B1594287D2B21B3DED51B53128EF5AFDF8B79CE25757A9678FA3AB2CFA44D57D/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f527108.vtt?ver=4|%EB%A7%90%EB%A0%88%EC%9D%B4%EC%8B%9C%EC%95%84%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BE7820B23047FA6735DA4B37AC7E3A628151B8DC1ED697F07FB0C434145102FA495904556D4B73A92615BAFB4EA026D9DF1B8C976EDE652A2377A82A78CA6BDB2/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f916710.vtt?ver=4|%EC%95%84%EB%9E%8D%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9BDF6F331BCD2760AFC7E8A95EEE4EB9B71C1CCC6FF5B434AD8165C598712A120B1FCD4BCA0339B4C3462F983F47B7E8BA5F81AEE227A9A094D735B6D0A3F6924C/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f788112.vtt?ver=4|%ED%8F%AC%EB%A5%B4%ED%88%AC%EA%B0%88%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9B7E4527EC08F7B5B3A2547B2B6C539BDAD5FD464DCBE45613792434F4049D943C8E000A533CA56B768CFE25DF10EB83D78E14FA9D7263EE9533235EF74D8EE864/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f469715.vtt?ver=4|%EC%8A%A4%ED%8E%98%EC%9D%B8%EC%96%B4|https://ltsaws.wetvinfo.com/svp_50125/01097AC97C5D53C2AB23D28EFF43BF4A9132556A74CF02BC4212CFEEDE813C3F1E923FC099DA6E0AB55E3880179D306B1927080A8F4073BD03EAE42DA5C6589C9B8B6BC55DC6CD1E047776036A09CD358997DA051CEF1F4580E7FD0566EB0235579928F72C5D3CA3D9C2D62B1B2414C5A63B88B886575A3CE29D4FA661A569EA64/gzc_1000117_0b53eqagyaaaomadyqb6ubsm2jgdnquaa2ka.f905716.vtt?ver=4",
    "data": "...",
    "type": "link"
}

Handle: "니급아적희환_2회 - 온라인 시청 - WeTV"

匹配到219段视频，开始下载
-- dispatcher/downloadHls
并行8线程下载
进度: [########################################] 100%    238.8/-MB 45.6MB/s 10s
正在合并视频
匹配到11个字幕，开始下载
并行8线程下载

----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\dispatcher.py", line 139, in download
    targetFileName = self.handleSubtitles(subtitles, fileName, targetFileName, headers)
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\dispatcher.py", line 108, in handleSubtitles
    self.downloader.downloadAll(subtitleUrls, subtitleNames, headers, self.hlsThreadCnt)
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\tools\downloader.py", line 174, in downloadAll
    self._waitUtilFinish()
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\tools\downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Desktop\동영상저장\webvideo-downloader-master\downloader\tools\downloader.py", line 123, in _downloadRange
    rangeSize = rangeSize or int(response.headers['Content-Length'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
----------------------------------------------------------------------------------------------------

**Comment by ChunlyShen** [comment]
Error messgae:
![2024-04-07 14 06 43](https://github.com/jaysonlong/webvideo-downloader/assets/101887887/60060ef8-9335-459e-92ac-de0f5b3b4bb2)

Solution:
1. go to  the path: "webvideo-downloader-master\downloader\tools", and open the "downloader.py" file
2. find "rangeSize = rangeSize or int(response.headers['Content-Length'])", and change to:
                    try:
                        rangeSize = rangeSize or int(response.headers['Content-Length'])
                    except KeyError:
                        rangeSize = len(response.content)

![2024-04-07 14 21 48](https://github.com/jaysonlong/webvideo-downloader/assets/101887887/1a76955d-125f-490c-b745-6c7b806f0eef)
