### ISSUE TITLE
下载腾讯720p视频出现错误

### ISSUE THREAD

**Issue by wonderkismet** [jaysonlong/webvideo-downloader#20]
Traceback (most recent call last):
  File "E:\Anaconda3\envs\newStock\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "E:\Anaconda3\envs\newStock\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda3\envs\newStock\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "E:\Anaconda3\envs\newStock\lib\site-packages\urllib3\connection.py", line 396, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "E:\Anaconda3\envs\newStock\lib\site-packages\urllib3\connection.py", line 406, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "E:\Anaconda3\envs\newStock\lib\ssl.py", line 334, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.SSLCertVerificationError: ("hostname 'vhot2.qqvideo.tc.qq.com' doesn't match either of '*.music.tc.qq.com', '*.kg.tc.qq.com', '*.stream.kg.qq.com', '*.tc.qq.com', '*.tsmusic.kg.qq.com', 'music.tc.qq.com'",)

**Comment by wonderkismet** [comment]
可能是就没有这个分辨率的内容，直接下载1080p就可以了。。。
