### ISSUE TITLE
爱艺奇视频下载不了了

### ISSUE THREAD

**Issue by JerryLiu122** [jaysonlong/webvideo-downloader#202]
下载视频之后，显示
Receive: {
    "fileName": "唐朝诡事录之西行-电视剧全集-完整版视频在线观看-爱奇艺",
    "linksurl": "https://cache.video.iqiyi.com/dash?tvid=6113807281206300&bid=600&vid=&src=01080031010000000000&vt=0&rs=1&uid=1626889005&ori=pcw&ps=0&k_uid=db0c64c04e897c852b7fddf570b9ed59&pt=0&d=0&s=&lid=0&cf=0&ct=0&authKey=cbab0770f748754d6bfeb77a02c9f81f&k_tag=1&dfp=a1761cbbdb84b1430fa000b55571774ea1ffa8333ad8092416b523b1e340456eaf&locale=zh_cn&pck=18hWobE0TUWpXKXXA51Zii7LdWYu6WPgym2d01H4Ni1g2tDPWcVaQjuPuU5wUh460V568&k_err_retries=0&up=&sr=1&qd_v=5&tm=1722123486747&qdy=u&qds=0&ppt=0&k_ft1=706436220846084&k_ft4=1162321298202628&k_ft2=262335&k_ft5=134217729&k_ft6=128&k_ft7=688390148&fr_300=120_120_120_120_120_120&fr_500=120_120_120_120_120_120&fr_600=120_120_120_120_120_120&fr_800=120_120_120_120_120_120&fr_1020=120_120_120_120_120_120&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a1761cbbdb84b1430fa000b55571774ea1ffa8333ad8092416b523b1e340456eaf%22%2C%22b_ft1%22%3A24%7D&ut=1&vf=eee24ecf25bd7ec421f12f60c78574fb",
    "data": "...",
    "type": "link"
}

Handle: "唐朝诡事录之西行-电视剧全集-完整版视频在线观看-爱奇艺"

----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lzy/Desktop/webvideo-downloader/downloader/dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "/Users/lzy/Desktop/webvideo-downloader/downloader/dispatcher.py", line 120, in download
    videoType, headers, audioUrls, videoUrls, subtitles = api.parseSingleUrl(url, data)
  File "/Users/lzy/Desktop/webvideo-downloader/downloader/api.py", line 122, in parseSingleUrl
    videoType, audioUrls, videoUrls, subtitles = parseIqiyiUrl(url, realData, headers)
  File "/Users/lzy/Desktop/webvideo-downloader/downloader/api.py", line 65, in parseIqiyiUrl
    program = data['data']['program']
KeyError: 'program'
----------------------------------------------------------------------------------------------------

**Comment by Shawnsyx** [comment]
歪个楼，我也是想用这个下载国际版爱奇艺的唐诡
