### ISSUE TITLE
爱奇艺获取不到视频

### ISSUE THREAD

**Issue by rayli1813** [jaysonlong/webvideo-downloader#208]
Listening on port 18888 for clients...

Receive: {
    "fileName": "拳击系统教学",
    "linksurl": "https://cache.video.iqiyi.com/dash?tvid=2413142800&bid=500&vid=&src=01010031010000000000&vt=0&rs=1&uid=1208570753&ori=pcw&ps=0&k_uid=erf75fugi7pxzondlo26v6ivmwiruf7o&pt=0&d=0&s=&lid=0&cf=0&ct=0&authKey=20f85eaef35e52c2f95542ec0742248d&k_tag=1&dfp=a18803bd7793e3482ea906f6abe3d9f4bd2b5d3e16dff23c57598778f427819d9c&locale=zh_cn&pck=1cw6yqzZIKghXvl1obSjOPCHHqqhxE1p43vdaD1f9EkSayH6bJOVGl35yJjjPwbrt5ee&k_err_retries=0&up=&sr=1&qd_v=5&tm=1732208917064&qdy=u&qds=0&ppt=0&k_ft1=706436220846852&k_ft4=1162321298202628&k_ft2=262335&k_ft5=134217729&k_ft6=128&k_ft7=755499012&fr_300=120_120_120_120_120_120&fr_500=120_120_120_120_120_120&fr_600=120_120_120_120_120_120&fr_800=120_120_120_120_120_120&fr_1020=120_120_120_120_120_120&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a18803bd7793e3482ea906f6abe3d9f4bd2b5d3e16dff23c57598778f427819d9c%22%2C%22b_ft1%22%3A24%7D&ut=0&vf=b12227744ec30fe8e4e0ac1347653640",
    "data": "...",
    "type": "link"
}

Handle: "拳击系统教学"

匹配到0段视频，开始下载
-- dispatcher/downloadHls
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sprgd11\webvideo-downloader\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sprgd11\webvideo-downloader\downloader\dispatcher.py", line 131, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, correct)
  File "C:\Users\sprgd11\webvideo-downloader\downloader\dispatcher.py", line 36, in _downloadHls
    fileNames = tools.generateFileNames(urls, tempFileBase)
  File "C:\Users\sprgd11\webvideo-downloader\downloader\tools\utils.py", line 153, in generateFileNames
    suffix = getSuffix(urls[0])
                       ~~~~^^^
IndexError: list index out of range

**Comment by haotime1688** [comment]
换了模板
