### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u7b2c'

### ISSUE THREAD

**Issue by leonguyen52** [jaysonlong/webvideo-downloader#29]
Hi, Please help to check this error. Any idea on how to fix it?

Traceback (most recent call last):
  File "dispatcher.py", line 164, in dispatch
    self.download(linksurl, fileName)
  File "dispatcher.py", line 129, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, concat)
  File "dispatcher.py", line 38, in _downloadHls
    tools.mergePartialVideos(fileNames, targetFileName, concat=concat)
  File "utils.py", line 250, in mergePartialVideos
    f.write(text)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u7b2c' in position 66: character maps to <undefined>

**Comment by jaysonlong** [comment]
This bug has been fixed for a long time, update please.
