### ISSUE TITLE
mac运行解析芒果405错误

### ISSUE THREAD

**Issue by jtning** [jaysonlong/webvideo-downloader#3]
Traceback (most recent call last):
  File "/Volumes/数据/Download/m3u8download/downloader/dispatcher.py", line 125, in dispatch
    self.download(linksurl, fileName)
  File "/Volumes/数据/Download/m3u8download/downloader/dispatcher.py", line 94, in download
    videoType, headers, audioUrls, videoUrls = api.preProcessUrl(linksurl)
  File "/Volumes/数据/Download/m3u8download/downloader/api.py", line 75, in preProcessUrl
    videoUrls = parseHls(url, headers)
  File "/Volumes/数据/Download/m3u8download/downloader/api.py", line 45, in parseHls
    content = tools.getText(url, headers)
  File "/Volumes/数据/Download/m3u8download/downloader/tools/utils.py", line 72, in getText
    response = request('GET', url, headers=headers)
  File "/Volumes/数据/Download/m3u8download/downloader/tools/utils.py", line 64, in request
    raise Exception('http响应: %d错误' % response.status_code)
Exception: http响应: 405错误

**Comment by jaysonlong** [comment]
单个视频还是所有视频都报错？请给出python版本 / 相关视频链接 / 是否已登录 / 是否VIP会员等信息以便排查。
