### ISSUE TITLE
希望能够支持一下优酷的下载

### ISSUE THREAD

**Issue by cjjdaq** [jaysonlong/webvideo-downloader#36]
主流的就差优酷了，希望能支持一下

**Comment by jaysonlong** [comment]
优酷有DRM视频加密，目前还没有什么解决办法

**Comment by cjjdaq** [comment]
@jaysonlong 
目前使用起来挺好的。但遇到个比较苦恼的问题，比如某个分片在下载过程中出错。比如遇到非200状态的，会导致整个m3u8下载中断，希望能加入自动重试功能。

**Comment by jaysonlong** [comment]
你说的是哪个视频网站

**Comment by cjjdaq** [comment]
腾讯，爱奇艺与芒果均会出现此问题。

**Comment by cjjdaq** [comment]
@jaysonlong 
比如这样：

匹配到265段视频，开始下载
-- dispatcher/downloadHls
并行64线程下载
进度: [                                                  ]  1%     44.9/-MB 22.4MB/s 1s  
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\vd\downloader\dispatcher.py", line 166, in dispatch
    self.download(url, fileName, data)
  File "d:\vd\downloader\dispatcher.py", line 130, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, concat)
  File "d:\vd\downloader\dispatcher.py", line 38, in _downloadHls
    self.downloader.downloadAll(urls, fileNames, headers, self.hlsThreadCnt)
  File "d:\vd\downloader\tools\downloader.py", line 174, in downloadAll
    self._waitUtilFinish()
  File "d:\vd\downloader\tools\downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\marscosmo\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\vd\downloader\tools\downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "d:\vd\downloader\tools\utils.py", line 101, in request
    % (method, url, response.status_code))
Exception: GET https://apd-f907b2e138b25d6c0249f404af9789ec.v.smtcdns.com/vipts.tc.qq.com/AAWyInFWvw9IRHjytU_ImcJgKdusU2cPe42XBpO66h2U/uwMROfz2r5xgoaQXGdGnC2df64gVTKzl5C_X6A3JOVT0QIb-/WOUj9FhUnFcRzYUrzm01u_2tloHSj9xdThSFGoFrf53vkAsp844In58pr1E7b9zqH2hTFJCGwDgUgkwwmaLoXx7YEUBW5DDK-U_47D1r9MUBmdOHFk6oVjp3dOlBG6DmDIGAiqA70G8VncFtJ47PwbYS6JLOhs9TLYa7d8NLorI/033_k0035bhtqtb.321004.2.ts?index=33&start=341720&end=349760&brs=7820800&bre=9561491&ver=4&token=a57f4d6c553e080e689d97f68940f01a http响应: 564错误

**Comment by jaysonlong** [comment]
564错误是因为超时，后面可以加入重连。其他错误码一般就没有必要重试了，通常都是因为链接过期了，重试也一样会报错。

**Comment by cjjdaq** [comment]
不一定是564，还有500错误的，还有其他。也不是因为链接过期。因为有的是刚打开的页面新添加的下载链接也会出现下载到中途出错。更好的是只要是非200都加入一下重试，可设置重试次数。重试次数完成后还不能正常下载的给个下载失败的打印信息，不然跳出老长的代码

**Comment by jaysonlong** [comment]
后续更新会考虑
