### ISSUE TITLE
Iqiyi Download

### ISSUE THREAD

**Issue by anfa14** [jaysonlong/webvideo-downloader#55]
[
![Untitled](https://user-images.githubusercontent.com/77573235/105339459-a5c3ae00-5c17-11eb-9d54-397eb4ad9802.jpg)
](url)

Could you help me solve this? Download link can not appear

**Comment by ali617768987** [comment]
me too

**Comment by alamia442** [comment]
work on me
but failed if download vip content

2021-01-21T13:19:56.340318+00:00 app[web.1]: Handle: "My First Love Is Secret Love Episode 3 | iQIYI"
2021-01-21T13:19:56.340445+00:00 app[web.1]: 
2021-01-21T13:19:56.352311+00:00 heroku[router]: at=info method=POST path="/" host=goodsore.herokuapp.com request_id=aac06580-a3cc-4ea0-854d-3af7f7a6e95e fwd="36.82.17.131" dyno=web.1 connect=1ms service=751ms status=200 bytes=156 protocol=http
2021-01-21T13:19:56.966166+00:00 app[web.1]: ----------------------------------------------------------------------------------------------------
2021-01-21T13:19:56.966579+00:00 app[web.1]: Traceback (most recent call last):
2021-01-21T13:19:56.966790+00:00 app[web.1]:   File "/app/downloader/dispatcher.py", line 169, in dispatch
2021-01-21T13:19:56.966791+00:00 app[web.1]:     self.download(url, fileName, data)
2021-01-21T13:19:56.966897+00:00 app[web.1]:   File "/app/downloader/dispatcher.py", line 120, in download
2021-01-21T13:19:56.966898+00:00 app[web.1]:     videoType, headers, audioUrls, videoUrls, subtitles = api.parseSingleUrl(url, data)
2021-01-21T13:19:56.967023+00:00 app[web.1]:   File "/app/downloader/api.py", line 118, in parseSingleUrl
2021-01-21T13:19:56.967024+00:00 app[web.1]:     videoType, audioUrls, videoUrls, subtitles = parseIqiyiUrl(url, realData, headers)
2021-01-21T13:19:56.967150+00:00 app[web.1]:   File "/app/downloader/api.py", line 61, in parseIqiyiUrl
2021-01-21T13:19:56.967150+00:00 app[web.1]:     program = data['data']['program']
2021-01-21T13:19:56.967314+00:00 app[web.1]: KeyError: 'program'
2021-01-21T13:19:56.967514+00:00 app[web.1]: ----------------------------------------------------------------------------------------------------

**Comment by anfa14** [comment]
> work on me
> but failed if download vip content
> 
> 2021-01-21T13:19:56.340318+00:00 app[web.1]: Handle: "My First Love Is Secret Love Episode 3 | iQIYI"
> 2021-01-21T13:19:56.340445+00:00 app[web.1]:
> 2021-01-21T13:19:56.352311+00:00 heroku[router]: at=info method=POST path="/" host=goodsore.herokuapp.com request_id=aac06580-a3cc-4ea0-854d-3af7f7a6e95e fwd="36.82.17.131" dyno=web.1 connect=1ms service=751ms status=200 bytes=156 protocol=http
> 2021-01-21T13:19:56.966166+00:00 app[web.1]: ----------------------------------------------------------------------------------------------------
> 2021-01-21T13:19:56.966579+00:00 app[web.1]: Traceback (most recent call last):
> 2021-01-21T13:19:56.966790+00:00 app[web.1]: File "/app/downloader/dispatcher.py", line 169, in dispatch
> 2021-01-21T13:19:56.966791+00:00 app[web.1]: self.download(url, fileName, data)
> 2021-01-21T13:19:56.966897+00:00 app[web.1]: File "/app/downloader/dispatcher.py", line 120, in download
> 2021-01-21T13:19:56.966898+00:00 app[web.1]: videoType, headers, audioUrls, videoUrls, subtitles = api.parseSingleUrl(url, data)
> 2021-01-21T13:19:56.967023+00:00 app[web.1]: File "/app/downloader/api.py", line 118, in parseSingleUrl
> 2021-01-21T13:19:56.967024+00:00 app[web.1]: videoType, audioUrls, videoUrls, subtitles = parseIqiyiUrl(url, realData, headers)
> 2021-01-21T13:19:56.967150+00:00 app[web.1]: File "/app/downloader/api.py", line 61, in parseIqiyiUrl
> 2021-01-21T13:19:56.967150+00:00 app[web.1]: program = data['data']['program']
> 2021-01-21T13:19:56.967314+00:00 app[web.1]: KeyError: 'program'
> 2021-01-21T13:19:56.967514+00:00 app[web.1]: ----------------------------------------------------------------------------------------------------

how can? is there any im missing?

**Comment by jaysonlong** [comment]
Long ago issue, try open a new issue if it still exists now
