### ISSUE TITLE
NoneType object is not callable

### ISSUE THREAD

**Issue by jyxjjj** [jaysonlong/webvideo-downloader#59]
```
Exception happened during processing of request from ('127.0.0.1', 54070)
Traceback (most recent call last):
  File "E:\python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Cache\Download\webvideo-downloader-2.0\downloader\tools\webserver.py", line 110, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "E:\python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\Cache\Download\webvideo-downloader-2.0\downloader\tools\webserver.py", line 133, in handle
    BaseHTTPRequestHandler.handle(self)
  File "E:\python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "E:\python37\lib\http\server.py", line 414, in handle_one_request
    method()
TypeError: 'NoneType' object is not callable
----------------------------------------
```
前两天好好的今天出问题
是不是腾讯视频那边更新了算法导致你这个失效了
但是这边看好像是py内置库socketserver的问题？
我是不是哪里弄错了
从何入手分析

**Comment by jaysonlong** [comment]
请给出下载页面的地址

**Comment by jyxjjj** [comment]
抱歉 抱歉 之前没有收到github的邮件提醒  看到您close 才注意到您已经回复了  
我当时使用的时候记得是腾讯视频全部视频都不行 别的站没有测试过的
但是网页的插件是正常的 我直接从网页插件获取了链接用ffmpeg下载了 
我当天就已经删除了该项目的文件 不知道还有什么可以帮到您的
