### ISSUE TITLE
哔哩哔哩个别视频下载失败

### ISSUE THREAD

**Issue by xiebruce** [jaysonlong/webvideo-downloader#60]
比如：[【美式发音】音标【口型舌位】教学高清合集](https://www.bilibili.com/video/BV1mE411f7sU?p=7)的第2、7、19集(1280×720，1920×1080)下载出错

```
Traceback (most recent call last):
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/dispatcher.py", line 133, in download
    targetFileName = self._downloadDash(audioUrls, videoUrls, fileName, headers)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/dispatcher.py", line 55, in _downloadDash
    self.downloader.multiThreadDownloadAll(audioUrls, audioNames, headers, \
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 192, in multiThreadDownloadAll
    self.multiThreadDownload(urls[0], fileNames[0], headers, threadCnt, fragmentCnt)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 188, in multiThreadDownload
    self._waitUtilFinish()
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "/Users/bruce/Softwares/webvideo-downloader/downloader/tools/utils.py", line 100, in request
    raise Exception('%s %s http响应: %d错误' \
Exception: GET https://xy110x85x55x82xy.mcdn.bilivideo.cn:4483/upgcxcode/39/66/122376639/122376639-1-30280.m4s?expires=1612537852&platform=pc&ssig=l5NPhtvN-a5d-_tbC6IK3w&oi=3072144514&trid=377678ad75bf4020ae1cc1342755a5c0u&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=11000018&mid=383364108&orderid=0,3&agrr=0&logo=A0000400 http响应: 416错误
----------------------------------------------------------------------------------------------------
```

**Comment by snowmanInChina** [comment]
我也是，下载B站视频出现同样的错误

**Comment by Q-uassia** [comment]
我也是同样错误

**Comment by jaysonlong** [comment]
我这边下载正常，没法复现
