### ISSUE TITLE
WebVideoDownloader v.2.2.2 still cannot work for iq.com

### ISSUE THREAD

**Issue by peedan** [jaysonlong/webvideo-downloader#90]
Receive: {
    "fileName": "my video",
    "linksurl": "https://cache-video.iq.com/jp/dash?tvid=4253584679034800&bid=600&vid=abe2c4788688b54418ebe6a4119bf1a5&src=01011021010010000000&vt=0&rs=1&uid=1382009961&ori=pcw&ps=0&k_uid=d610cba549ac09d01b6d5a4bb80b2ed4&pt=0&d=0&s=&lid=1&slid=2&cf=2&ct=&authKey=a6dd99a2c2cb2b122b6297c73a561c3f&k_tag=1&ost=0&ppt=0&dfp=a065b80b825ca75610be311a5b7cc4ad3c116ad4f5a57613336daae288b8adfcf0&prio=%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D&k_err_retries=0&up=&su=2&applang=zh_tw&sver=2&qd_v=2&tm=1627021671325&qdy=a&qds=0&k_ft1=141287244169348&k_ft4=8196&k_ft5=1&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a065b80b825ca75610be311a5b7cc4ad3c116ad4f5a57613336daae288b8adfcf0%22%7D&callback=Q7fed45beb788c48fc39efd8668e1bc95&ut=100058&vf=13e4e5992daf45077581cd5f4bb8b978",
    "data": "...",
    "type": "link"
}

Handle: "my video"

Traceback (most recent call last):
  File "d:\webvideo-downloader-master\webvideo-downloader-master\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "d:\webvideo-downloader-master\webvideo-downloader-master\downloader\dispatcher.py", line 120, in download
    videoType, headers, audioUrls, videoUrls, subtitles = api.parseSingleUrl(url, data)
  File "d:\webvideo-downloader-master\webvideo-downloader-master\downloader\api.py", line 118, in parseSingleUrl
    videoType, audioUrls, videoUrls, subtitles = parseIqiyiUrl(url, realData, headers)
  File "d:\webvideo-downloader-master\webvideo-downloader-master\downloader\api.py", line 60, in parseIqiyiUrl
    data = json.loads(tools.getText(url, headers))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

================================================
Blue button appears again in iq.com but it still cannot download. 
Message showed above.
Please debug, thanks a lot.

**Comment by peedan** [comment]
I know the reasons that why it cannot work.
I forgot to update daemon.py & api.py.
Thanks for jaysonlong's hard work.
