### ISSUE TITLE
download's interrupted after updating (iq.com)

### ISSUE THREAD

**Issue by luuurc** [jaysonlong/webvideo-downloader#94]
I have already update the new files, but now some of the downloading on iq.com cannot be finished, could anyone solve this? 

For example, the download process of this video (https://www.iq.com/play/the-detectives'-adventures-2021-07-30-v94msul0o0?frmrp=home&frmb=continue_watching&frmrs=2#) is interrupted at around 30%.

Traceback (most recent call last):
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 131, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, correct)
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 39, in _downloadHls
    self.downloader.downloadAll(urls, fileNames, headers, self.hlsThreadCnt)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 174, in downloadAll
    self._waitUtilFinish()
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "F:\webvideo-downloader\downloader\tools\utils.py", line 100, in request
    raise Exception('%s %s http响应: %d错误' \
Exception: GET http://data.video.iqiyi.com/videos/vts/20210730/2d/e5/147bab45310650ab8d07d43a557a950c.ts?start=0&end=2494384&contentlength=2494384&sd=734680&qdv=1&qd_uid=34007521223&qd_tvid=3153013136049100&qd_vip=1&qd_src=01010031010011000000&qd_tm=1627870794426&qd_ip=0&qd_p=0&qd_k=18d647f5087d868ada641496a6167d40&ve=&sgti=47_85544fde2a54f601ded9696c5398dc81_1627870794464&dfp=&qyid=85544fde2a54f601ded9696c5398dc81&qd_vipres=0&qd_sc=75b0db7680fabdb38c657140ac1562a2 http响应: 404错误

**Comment by charles0568** [comment]
今天開始好像都沒法完整下載了
并行8线程下载
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'cp950' codec can't encode character '\u54cd' in position 513: illegal multibyte sequence
Call stack:
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 80, in _worker
   work_item.run()
  File "C:\Users\Charles3F\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\webvideo-downloader\downloader\tools\downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "C:\webvideo-downloader\downloader\tools\utils.py", line 98, in request
    reqLogger and reqLogger.error('%s %s http响应: %d错误' \
Message: 'GET http://data.video.iqiyi.com/videos/vts/20210808/56/94/ab59a620f1583db2c9378beea0afb43b.ts?start=10955512&end=16093364&contentlength=5137852&sd=23320&qdv=1&qd_uid=2613945094&qd_tvid=4182994084521400&qd_vip=1&qd_src=01011021010010000000&qd_tm=1628427116586&qd_ip=0&qd_p=0&qd_k=5e2621ff2c5f922dcd430f9b01ea67bf&ve=&sgti=47_ffa04326a1928fabe8fa2676850157e9_1628427119083&dfp=&qyid=ffa04326a1928fabe8fa2676850157e9&qd_vipres=2&qd_sc=99f340c18b8ac8ad790f996d5e255404 http 响应: 500错误'
Arguments: ()

**Comment by charles0568** [comment]
修改了 utils.py 
    if response.status_code > 699:  <===原本數值為299 改為699 居然就好了
        reqLogger and reqLogger.error('%s %s http响应: %d错误' \
            % (method, url, response.status_code))
        raise Exception('%s %s http响应: %d错误' \
            % (method, url, response.status_code))
    return response

**Comment by luuurc** [comment]
> I have already update the new files, but now some of the downloading on iq.com cannot be finished, could anyone solve this?
> 
> For example, the download process of this video (https://www.iq.com/play/the-detectives'-adventures-2021-07-30-v94msul0o0?frmrp=home&frmb=continue_watching&frmrs=2#) is interrupted at around 30%.
> 
> Traceback (most recent call last):
> File "F:\webvideo-downloader\downloader\dispatcher.py", line 167, in dispatch
> self.download(url, fileName, data)
> File "F:\webvideo-downloader\downloader\dispatcher.py", line 131, in download
> targetFileName = self._downloadHls(videoUrls, fileName, headers, correct)
> File "F:\webvideo-downloader\downloader\dispatcher.py", line 39, in _downloadHls
> self.downloader.downloadAll(urls, fileNames, headers, self.hlsThreadCnt)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 174, in downloadAll
> self._waitUtilFinish()
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 105, in _waitUtilFinish
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
> raise self.threadPool.exception
> File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "F:\webvideo-downloader\downloader\tools\downloader.py", line 122, in _downloadRange
> response = utils.request("GET", url, headers=headers, stream=True)
> File "F:\webvideo-downloader\downloader\tools\utils.py", line 100, in request
> raise Exception('%s %s http响应: %d错误'
> Exception: GET http://data.video.iqiyi.com/videos/vts/20210730/2d/e5/147bab45310650ab8d07d43a557a950c.ts?start=0&end=2494384&contentlength=2494384&sd=734680&qdv=1&qd_uid=34007521223&qd_tvid=3153013136049100&qd_vip=1&qd_src=01010031010011000000&qd_tm=1627870794426&qd_ip=0&qd_p=0&qd_k=18d647f5087d868ada641496a6167d40&ve=&sgti=47_85544fde2a54f601ded9696c5398dc81_1627870794464&dfp=&qyid=85544fde2a54f601ded9696c5398dc81&qd_vipres=0&qd_sc=75b0db7680fabdb38c657140ac1562a2 http响应: 404错误

**Comment by charles0568** [comment]
i download this video is okay~
https://www.iq.com/play/%E8%90%8C%E6%8E%A2%E6%8E%A2%E6%8E%A2%E6%A1%88-2021-07-30-xe5l3uj44c?frmrp=search&frmb=list&frmrs=title
