### ISSUE TITLE
fail to download 1080p on iq.com

### ISSUE THREAD

**Issue by luuurc** [jaysonlong/webvideo-downloader#96]
the download process may be interrupted when downloading 1080p videos on iq.com
for the same video below, 720p version can be downloaded successfully
Here's the error report, downloads stopped at 25%

Handle: "The Blooms at RUYI Pavilion Episode 1 watch online | iQiyi"

匹配到332段视频，开始下载
-- dispatcher/downloadHls
并行8线程下载
进度: [##########                              ] 25%    181.0/-MB  1.9MB/s 52s
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 167, in dispatch
    self.download(url, fileName, data)
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 131, in download
    targetFileName = self._downloadHls(videoUrls, fileName, headers, correct)
  File "F:\webvideo-downloader\downloader\dispatcher.py", line 39, in _downloadHls
    self.downloader.downloadAll(urls, fileNames, headers, self.hlsThreadCnt)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 174, in downloadAll
    self._waitUtilFinish()
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 105, in _waitUtilFinish
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 130, in _downloadRange
    raise self.threadPool.exception
  File "C:\Users\ywiqi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\webvideo-downloader\downloader\tools\downloader.py", line 122, in _downloadRange
    response = utils.request("GET", url, headers=headers, stream=True)
  File "F:\webvideo-downloader\downloader\tools\utils.py", line 100, in request
    raise Exception('%s %s http响应: %d错误' \
Exception: GET http://data.video.iqiyi.com/videos/vts/20201021/a6/f0/e7abb7cc9296372877eb4bf9a121e7b9.ts?start=3256724&end=4487372&contentlength=1230648&sd=748680&qdv=1&qd_uid=34007521223&qd_tvid=1529429459670600&qd_vip=1&qd_src=01010031010011000000&qd_tm=1628738786098&qd_ip=b7b24494&qd_p=b7b24494&qd_k=0781459e67b86b4840a7a911337306fa&ve=&sgti=47_85544fde2a54f601ded9696c5398dc81_1628738785398&dfp=&qyid=85544fde2a54f601ded9696c5398dc81&qd_vipres=0&qd_sc=146503052dfbfb0146ea47531b283036 http响应: 404错误

**Comment by charles0568** [comment]
i download this video is okay ~https://www.iq.com/play/%E5%A6%82%E6%84%8F%E8%8A%B3%E9%9C%8F-1-1vpmp4bm5dg?frmrp=search&frmb=list&frmrs=fenji_button
Receive: {
    "fileName": "如意芳霏 1 線上看 | iQiyi 愛奇藝",
    "linksurl": "https://cache-video.iq.com/dash?tvid=6785220093815000&bid=600&vid=abe2c4788688b54418ebe6a4119bf1a5&src=01011021010010000000&vt=0&rs=1&uid=2613945094&ori=pcw&ps=0&k_uid=ffa04326a1928fabe8fa2676850157e9&pt=0&d=0&s=&lid=&slid=0&cf=&ct=&authKey=b2b891f4dd2c64aa8633b402da36f720&k_tag=1&ost=0&ppt=0&dfp=a1a0b0c14ae7f1585dae1d5f971c2a5a106deaf905762531d81057dc30c5dd815b&prio=%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D&k_err_retries=0&up=&su=2&applang=zh_tw&sver=2&qd_v=2&tm=1628745124601&qdy=a&qds=0&k_ft1=141287244169348&k_ft4=8196&k_ft5=1&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a1a0b0c14ae7f1585dae1d5f971c2a5a106deaf905762531d81057dc30c5dd815b%22%7D&ut=100058&vf=c0f621f3824623889492b4f041f18a01",
    "data": "...",
    "type": "link"
}

Handle: "如意芳霏 1 線上看 | iQiyi 愛奇藝"

匹配到331段视频，开始下载
-- dispatcher/downloadHls
并行8线程下载
进度: [########################################] 100%    568.9/-MB 13.9MB/s 34s
正在合并视频
匹配到5个字幕，开始下载
并行8线程下载
进度: [########################################] 100%      0.2/-MB   36KB/s 2s
正在集成字幕
Finish: \\192.168.1.99\Download\Dramas\如意芳霏 1 線上看 _ iQiyi 愛奇藝.mp4

**Comment by luuurc** [comment]
> % 568.9/-MB

I have update every file now, but it's still failed when downloading 1080p videos, 720p is ok~

**Comment by jaysonlong** [comment]
i can't verify or fix it due to have no vip account
